export const movies = [
    {title: "The Avengers",
    plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    poster: "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",          
    price: 199,
    rating: '8.4',
    star: 0,
    fav: false,
    cart: false},
    
    {title: "The Dark Knight",
    plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    price: 249,
    rating: '9.0',
    star: 0,
    fav: false,
    cart: false},

    {title: "Iron Man",
    plot: "After being held captive in an Afghan cave, billionaire engineer Tony starsk creates a unique weaponized suit of armor to fight evil.",
    poster: "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg",
    price: 139,
    rating: '7.9',
    star: 0,
    fav: false,
    cart: false},

    {title: "The Avengers",
    plot: "Supernatural powers shown in the movie.",
    poster: "",
    price: 199,
    rating: 8.9,
    star: 0,
    fav: false,
    cart: false},

    {title: "The Avengers",
    plot: "Supernatural powers shown in the movie.",
    poster: "",
    price: 199,
    rating: 8.9,
    star: 0,
    fav: false,
    cart: false},

    {title: "The Avengers",
    plot: "Supernatural powers shown in the movie.",
    poster: "",
    price: 199,
    rating: 8.9,
    star: 0,
    fav: false,
    cart: false}
]