export const movies = [
    {title: "The Avengers",
    plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    poster: "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",          
    price: 199,
    rating: '8.4',
    star: 0,
    fav: false,
    cart: false},
    
    {title: "The Dark Knight",
    plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    price: 249,
    rating: '9.0',
    star: 0,
    fav: false,
    cart: false},

    {title: "Iron Man",
    plot: "After being held captive in an Afghan cave, billionaire engineer Tony starsk creates a unique weaponized suit of armor to fight evil.",
    poster: "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg",
    price: 139,
    rating: '7.9',
    star: 0,
    fav: false,
    cart: false},

    {title: "Black Panther",
    plot: "Thousands of years ago, five African tribes war over a meteorite containing the metal vibranium. One warrior ingests a heart-shaped herb affected by the metal and gains superhuman abilities, becoming the first Black Panther. He unites all but the Jabari Tribe to form the nation of Wakanda.",
    poster: "https://image.tmdb.org/t/p/original/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    price: 299,
    rating: '8.9',
    star: 0,
    fav: false,
    cart: false},

    {title: "Captain Marvel",
    plot: "In 1995, on the Kree Empire's capital planet of Hala, Starforce member Vers suffers from amnesia and recurring nightmares involving an older woman. Yon-Rogg, her mentor and commander, trains Vers to control her abilities, while the Supreme Intelligence, the artificial intelligence that rules the Kree, urges her to keep her emotions in check.",
    poster: "https://image.tmdb.org/t/p/original/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
    price: 269,
    rating: '7.7',
    star: 0,
    fav: false,
    cart: false},

    {title: "Spider-man: No Way Home",
    plot: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    poster: "https://th.bing.com/th/id/OIP.9IBYeqL7wGKtxsPLffGxPgHaLH?pid=ImgDet&rs=1",
    price: 279,
    rating: '9.0',
    star: 0,
    fav: false,
    cart: false}
]